### Homework 12
##### Name: Thu Trang
##### Student ID: 11230595
##### Class: DSEB65A

In [1]:
!git clone https://github.com/hung20gg/grade_func.git
!cd grade_func && git pull

fatal: destination path 'grade_func' already exists and is not an empty directory.
Already up to date.


In [2]:
from grade_func.grader import test_func_from_file

## Question 1 (1.25p): Count Word Frequency 
Write a function count_word_frequency(file) that reads a text file and counts the frequency of each word.

If the file does not exist, the function should return the string: 
- Error: File does not exist.

Example:
- Input: file.txt
- Output (dictionary): {'hello': 2, 'world': 1}

In [3]:
import nltk

def count_word_frequency(file):
    try:
        with open(file) as text_input:
            text = text_input.read()
    except FileNotFoundError:
        return "Error: File does not exist."

    words = nltk.word_tokenize(text)
    words_freq = {}
    for word in words:
        if word in words_freq:
            words_freq[word] += 1
        else:
            words_freq[word] = 1
    
    return words_freq

In [4]:
q1 = test_func_from_file(count_word_frequency, 'hw12_q_1.txt')
q1

FileNotFoundError: [Errno 2] No such file or directory: 'grade_func/input/hw12_q_1.txt'

## Question 2: Append Integers to File
Write a function append_integers_to_file(integers, file) that appends a list of integers to a file.

If there’s an error writing to the file, the function should return: 
- Error: Unable to write to the file.

Example:
- Input: [1, 2, 3, 4, 5], file.txt
- Output: 'Data successfully appended to the file.'

In [8]:
def append_integers_to_file(integers, file):
    try:
        with open(file, 'a') as f:
            for integer in integers:
                f.write(f"{integer}\n")
        return "Data successfully appended to the file."
    except Exception:
        return "Error: Unable to write to the file."

In [ ]:
q2 = test_func_from_file(append_integers_to_file, 'hw12_q_2.txt')
q2

## Question 3: Safe Division
Write a function safe_division(tup) that performs division of two numbers. Input is a tuple (a,b)

If division by zero is attempted, return: 
- Cannot divide by zero.

Example:
- Input: (10,0)
- Output: 'Cannot divide by zero.'
- Input: (10, 2)
- Output: 5.0

In [11]:
def safe_division(tup):
    if tup[1] == 0:
        print(f"Cannot divide by zero")
    else:
        print(tup[0]/tup[1])


In [13]:
q3 = test_func_from_file(safe_division, 'hw12_q_3.txt')
q3

Total tests: 5
Passed tests: 0


0.0

## Question 4: Copy File Contents
Write a function copy_file_contents(src_file, dest_file) that copies the content from one file to another.

If the source file does not exist, return: 
- Error: Source file not found.

Example:
- Input: 'source.txt', 'destination.txt'
- Output: 'Copy successful.'


In [14]:
def copy_file_contents(src, dest):
    try:
        with open(src) as file_input:
            text = file_input.read()
    except Exception:
        return "Error: Unable to write to the file."
        
    with open(dest) as file_copy:
        text.write(file_copy)
        return "Copy successful"
    

In [9]:
# copy_file_contents('hw12_q_4.txt', "hw12_q_4_dest.txt")

## Question 5: NumPy Array Attributes
Write a function numpy_array_attributes(lis) that prints the shape, dimensions, and size of a NumPy array. 
- Input is a list. 
- Output is a list [shape, dimensions, size]

Example:
- Input: [1, 2, 3, 4, 5]
- Output: [(5,),1,5]

In [5]:
import numpy as np
def numpy_array_attributes(lis):
    arr = np.array(lis)

    shape = arr.shape
    dimensions = arr.ndim
    size = arr.size

    return [shape, dimensions, size]

In [6]:
q5 = test_func_from_file(numpy_array_attributes, 'hw12_q_5.txt')
q5

Total tests: 5
Passed tests: 0


0.0

## Question 6 (1.25p)): Modify Subarray
Write a function modify_subarray(neslis) that modifies a 2x2 subarray of a 3x3 NumPy array without copying. The modification should change all elements in the subarray to 0.

- Input: nested list
- Output: [modified subarray, original array]

If the input is not a 3x3 NumPy array, print an error message: - "Error: Input must be a 3x3 NumPy array."

Example:
- Input:[[4, 1, 7],
        [6, 5, 3],
        [8, 2, 9]]
- Ouput: [[[0 0]
 [0 0]],
 [[0 0 7]
 [0 0 3]
 [8 2 9]]]

In [2]:
import numpy as np

def modify_subarray(neslis):
    neslis = np.array(neslis)
    
    if neslis.shape != (3, 3):
        print("Error: Input must be a 3x3 NumPy array.")
        return
    
    neslis[0:2, 0:2] = 0
    
    modified_subarray = neslis[0:2, 0:2]
    
    return [modified_subarray.tolist(), neslis.tolist()]

neslis = [[4, 1, 7], [6, 5, 3], [8, 2, 9]]
print(modify_subarray(neslis))

[[[0, 0], [0, 0]], [[0, 0, 7], [0, 0, 3], [8, 2, 9]]]


In [ ]:
q6 = test_func_from_file(modify_subarray, 'hw12_q_6.txt')
q6

## Question 7 (1.25p): Extract Row and Column
Write a function extract_row_and_column(neslis) that extracts the first row and the first column from a given NumPy array. The input array can have any shape. If the array is too small to extract a row or a column, print an error message.

If the input array has fewer than 2 rows or columns, print: 
- "Error: Array must have at least 2 rows and 2 columns."


- Input: nested list
- Output: [first row, first column]

Example:
- Input: [[3, 8, 5, 2],
 [9, 1, 4, 7],
 [6, 5, 3, 8]]
- Output: [[3 8 5 2],[3 9 6]]



In [20]:
def extract_row_and_column(neslis):
    array = np.array(neslis)

    if array.shape[0] < 2 or array.shape[1] < 2:
        print("Error: Array must have at least 2 rows and 2 columns.")
        return
    
    first_row = array[0, :]
    first_column = array[:, 0]

    return [first_row.tolist(), first_column.tolist()]


In [ ]:
q7 = test_func_from_file(extract_row_and_column, 'hw12_q_7.txt')

## Question 8: Slice and Modify Array
Write a function slice_and_modify_array(neslis) that slices a 1D array and modifies the elements from index 2 to 5.

Verify if the result is a view or a copy by checking if the original array is changed.
- Input:  nested list
- Output: [sliced array, modified array, original array]

Example:
- Input: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
- Output: [[2, 3, 4], [0, 0, 0], [0, 1, 0, 0, 0, 5, 6, 7, 8, 9]]



In [20]:
def slice_and_modify_array(neslis):
    sliced_array = neslis[2:5]
    modified_array = [0] * len(sliced_array)
    neslis[2:5] = modified_array
    
    return [sliced_array, modified_array, neslis]

input_array = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
output = slice_and_modify_array(input_array)
print(output)

[[2, 3, 4], [0, 0, 0], [0, 1, 0, 0, 0, 5, 6, 7, 8, 9]]


In [ ]:
q8 = test_func_from_file(slice_and_modify_array, 'hw12_q_8.txt')
q8

## Question 9 (1.25p): Get Diagonal Elements
Write a function get_diagonal_elements(neslis) that retrieves the elements on the main diagonal of a NumPy array.


If the input is not a square NumPy array, print an error message: 
- "Error: Input must be a square NumPy array."

Example:
- Input:
[[2, 3, 4],
 [5, 6, 7],
 [8, 9, 1]]
- Output: [2, 6, 1]

In [24]:
def get_diagonal_elements(neslis):
    if not isinstance(neslis, np.ndarray):
        print("Error: Input must be a square NumPy array.")
        return
    
    if neslis.shape[0] != neslis.shape[1]:
        print("Error: Input must be a square NumPy array.")
        return
    
    diagonal_elements = np.diagonal(neslis)
    return diagonal_elements.tolist()


In [ ]:
q9 = test_func_from_file(get_diagonal_elements, 'hw12_q_9.txt')
q9